### PR TITLE
feature: 📍 Added travel page

### LINKED ISSUE #13: Add visited places page 📌
Add a new page (/travel) to display a map that shows all the visited places a person has been!

Make it easy for multiple places to be added at any time without modifying a lot of the code.

### PR DESCRIPTION
**Pull request by Diegogtz03**
#21 Added travel page (/travel)

I used [Mapboxs'](https://docs.mapbox.com/mapbox-gl-js/guides/) API to render a dark mode map into our website! I needed to use a public API key, same which I saved in our environment variables, but if you dig deep enough in the DOM, it's still visible. Anyways, the key only has public access so it won't do any damage if anyone tries to use it.

How to add new locations to the map:

1. In travel.js you will find the next constant:
```javascript
 const visitedPlaces = [
    {
      latitude: 37.7829,
      longitude: -122.4190,
      label: "Travel place 1",
      tooltip: `I visited San Francisco in 2019`
    },
    {
      latitude: 37.7829,
      longitude: 115.4190,
      label: "Travel place 2",
      tooltip: `I visited San Francisco in 2019`
    },
    ...
];
``` 
2. Delete this data and in the same format add all the places you would like with the information corresponding to the place visited. You can use the `` to create multi-line text to appear in the tooltips in the map!

We can also change any of the maps configuration changing the following code:

```javascript
  Mapkick.options = {
    style:'mapbox://styles/mapbox/navigation-night-v1', 
    zoom: 0.8, 
    center: [0, 40],
    tooltips: {html: true, hover: false},
    markers: {color: "#f84d4d"},
    label: {color: "#f84d4d"},
    textColor: "#f84d4d"
  };

```

### CODE REVIEW

**Review by YeyoM — CHANGES_REQUESTED** [review]
Diego, I think it would be a better idea to use maplibre instead of mapbox because maplibre is a free alternative, where mapbox is only free for starters but can scale up in cost.

I tested it locally, and the changes we might need for this are quite simple:

Add the following to travel.html instead of the mapbox tags
```html
    <link href="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css" rel="stylesheet" />
    <script src="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js"></script>
```

Delete the following line from travel.js:
```js
  // set the token given by Mapbox
  mapboxgl.accessToken = token;
```

And also in travel.js (Mapkick.options object) change:
```js
    style:'mapbox://styles/mapbox/navigation-night-v1', 
```
for
```js
    style:'https://demotiles.maplibre.org/style.json', 
```

As a result we might also delete the "token" argument from the "loadMap()" function, both in travel.html and travel.js

**Comment by Diegogtz03** [comment]
Awesome!

I had some trouble yesterday with the rendering of the map using Maplibre yesterday but I'll definitely give it a try with the info you provided!! 

A way better choice for us now!

Will make another PR with these changes!

**Comment by YeyoM** [comment]
Okey, any problem you might encounter please let me know!

**Comment by Diegogtz03** [comment]
I did the changes and it works! 

The only thing is that I feel like the light themed map has a very high contrast in comparison with the dark themed one that MapBox does provide... I tried multiple ways to change the style of the map but all of the workable solutions needed some sort of API key that ended up in the same thing as MapBox...

I did a little digging around the pricing of MapBox and apparently it's a free tier as long as we don't surpass 50,000 loads per month (This does count if we reload the page 😢). (I'll attach some images)

Screenshot 2023-06-23 at 12 58 55 p m
Screenshot 2023-06-23 at 12 58 31 p m


**In this case I see some options we have...**

- We could continue using Mapbox and trust the 50,000 monthly loads
- We could make a whole API change to google maps API which apparently does require an API key but it's totally free and we have unlimited usage of it
- We could just use Maplibre but stay with the light themed map


Let me know what you think! 😀

**Comment by YeyoM** [comment]
There is a way to change the theme of Maplibre, it will be kind of tricky but it may work, we can download https://demotiles.maplibre.org/style.json and change the color schemes to our choice, after that we just place the document on our project and it should work. 

But for now, we can stick to mapbox and in a future issue I can work on theming Maplibre's map and decide which one would be better!

**Comment by Diegogtz03** [comment]
You're right! I'm currently modifying the colors, let me create a quick dark theme and I'll make the final PR!

Thanks!

**Review by YeyoM — APPROVED** [review]

**Comment by YeyoM** [comment]
Alright, its up to you, maybe when finished, take some screenshots to decide!

**Comment by Diegogtz03** [comment]
Screenshot 2023-06-23 at 1 34 10 p m

**Comment by YeyoM** [comment]
Looks nice, but maybe the color palette could improve, for now we can merge to main and in a future issue I can redesign a new palette that fits better the page!

**Comment by Diegogtz03** [comment]
Awesome! Completely agree!

**Pull request merged**
